// The full canonical LSQ stage funnel, in display order. Single source of
// truth for the stage strip (LeadStageStrip), the drip-step stage picker, and
// the /api/lsq/stages fallback — so EVERY stage shows in the strip even when
// no contact currently sits in it (the API used to hide zero-count stages).
// Pure constant; safe to import on both client and server.
export const ALL_LEAD_STAGES = [
  "Prospect",
  "Engaged",
  "Pending First Contact",
  "Photo Awaited",
  "Photos Received",
  "Photo Approved",
  "Photo Disapproved",
  "Graft Evaluation",
  "Graft Evaluation Awaited",
  "Graft Evaluation Completed",
  "Call Back",
  "Follow Up",
  "Package Shared",
  "Consultation",
  "Consultation Done",
  "Follow up for Booking",
  "Booking Done",
  "Refund Requested",
  "Refund Initiated",
  "Refund Rescued",
  "Refunded Done",
  "Lead Bucket",
  "Other Services",
  "Hyderabad leads",
  "DNP",
  "Surgery Date Awaited",
  "Surgery Date Confirmed",
  "Surgery Date Aligned",
  "Surgery Date Postponed",
  "Not Eligible for HT",
  "Hairloss Treatment/Medication",
  "Backlog",
  "Planning for Second Session",
  "Happy Patient",
  "Follow_Up for Medicine",
  "Call Back for Medicine",
  "Interested To Buy for Medicine",
  "Consultation for Medicine",
  "DNP_Medicine",
  "Order Confirmed",
  "Order Received",
  "Order Placed",
  "Abandoned Cart",
  "HT Done/Medicine",
  "Location Constraint",
  "Pricing Concern",
  "Invalid Number",
  "Not Enquired",
  "Hung Up",
  "Call Back Time",
  "Future Follow Up",
  "Wrong Number",
  "Language barrier",
  "L1 Fall Out",
  "Interested in HT",
  "HT Care Follow Up",
  "HT Care & Medicine",
  "Medicine Suggested",
  "Repeated Order",
  "Order Discussion",
  "Order Fulfillment",
  "Surgery Discussion",
  "Order Confirmed by Bot",
  "Order Conformed by WA Bot",
  "Lost Lead",
  "Future Planning",
  "Winter Planning",
  "HT Done",
] as const;
